trigger:
- main

resources: 
- repo: self

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  tag: '$(Build.BuildId)'

steps:

- task: DotNetCoreCLI@2
  displayName: Build
  inputs: 
    command: build
    projects: 'AzureApp.sln'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs: 
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
    

- task: Docker@2
  inputs:
    containerRegistry: 'acr-connection'
    repository: 'azureapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(tag)
      latest
